version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mysql

  apache_php:
    image: php:apache
    container_name: apache_php_container
    ports:
      - "4500:80"
    volumes:
      - C:/Users/Aluno/Desktop/aham/api:/var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "docker-php-ext-install pdo_mysql && apache2-foreground"
      
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Aluno/Desktop/hum/mysql_data:/var/lib/mysql
    command: --bind-address=0.0.0.0